### ISSUE TITLE
Feature requests for advanced report handling 

### ISSUE THREAD

**Issue by DigitalFriends** [Mesharsky/Simple-Reports#4]
Been testing your plugin for some time now, working flawlessly. I really like it, it's clean!

I got some feature requests you could look into. 

- Add reactions to a report, so when an admins takes the report he can display it to others, and when he is finished with it, he can press a second reaction so others can see that its been handled

- Possibly look into building a discord bot for this so you can extend the discord functionality a bit more, a report could have multiple statuses, like "New, handled, finished" etc. If you have a bot, the bot could retract the report from the channel it was sent to when its out of new/handled status.

- The bot could have a default message at the top of the report channel, where admins can react to the message in order to get notified or not by new incoming reports, this way admins can easily jump in and out of the report role

Just my two cents, let me know if something is unclear or if i can help you out with anything!

**Comment by Mesharsky** [comment]
Hello! 
Thank you for a good feedback

Your ideas are great, but their implementation requires a complete rewrite of the entire plugin and creating a discord bot, which is completely different from the idea of ("Simple Reports")

Because integration with Discord would consist in sending requests to the server instead of reading only information from the server.

It would require a completely separate plugin and a lot of work where I don't even know if I could do it.
Also i have no experience and idea how to create discord bot on it's own. Unless there will be some magic API & Tool that will fully allow me to do that (from my knowledge no such a thing exists).
